// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// dotenv/config só carrega .env por padrão — Next.js também usa .env.local
// (maior precedência), então carregamos ambos aqui para a CLI do Prisma
// enxergar as mesmas variáveis que a app usa em runtime.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // A CLI (migrate/studio/db seed) precisa de uma conexão direta/sessão —
    // o pooler em modo transaction (DATABASE_URL, usado em runtime pelo
    // adapter-pg em src/lib/prisma.ts) não suporta os advisory locks que o
    // Prisma Migrate usa.
    url: process.env["DIRECT_URL"],
  },
});
